branches:
  only:
    - master

language: cpp

git:
  depth: 10

cache:
  - ../mysql-5.5

jobs:
  include:
    # Linux
    - name: 'Build on Linux (Ubuntu 14.04)'
      os: linux
      dist: trusty
      python: "3.6"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
            - llvm-toolchain-trusty-8
          packages:
            - lib32stdc++6
            - lib32z1-dev
            - libc6-dev-i386
            - linux-libc-dev
            - g++-multilib
      before_install:
        - export WDIR=$(pwd)
        - export PYTHON_VER=3.6.8
        - export PATH=$HOME/.local/bin:$WDIR/../clang-9/usrbin:$PATH
        - if [[ ! -s "$HOME/.pythonz/etc/bashrc" ]]; then (curl -kL https://raw.github.com/saghul/pythonz/master/pythonz-install | bash); fi
        - source $HOME/.pythonz/etc/bashrc && $(pythonz locate $PYTHON_VER) --version >/dev/null 2>&1 || pythonz install $PYTHON_VER
        - mkdir -p $HOME/.local/bin/ && ln -s $(pythonz locate $PYTHON_VER) $HOME/.local/bin/python
        - python -m pip install --upgrade pip
        - python -m pip install requests uritemplate discord-webhook
        - if [ ! -d "../clang-9/bin" ]; then (curl -SL https://bitbucket.org/rom4s/other.get/downloads/clang-9-ubuntu-14.04.tar.xz | tar -xJC ..); fi
      script:
        - git clone 'https://github.com/rom4s/sourcemod-css34-builder' ../builder
        - ../builder/run/linux.sh
      cache:
        - ../clang-9
        - $HOME/.pythonz
    # Windows
    - name: 'Build on Windows'
      os: windows
      python: "3.8"
      before_install:
        - export WDIR=$(pwd)
        - export PATH=/C/Python38:/C/Python38/Scripts:$PATH
        - if [ ! -d "/C/Python38/Scripts" ]; then (choco install python --version=3.8.0); fi
        - python -m pip install --upgrade pip
        - python -m pip install requests uritemplate discord-webhook
      script:
        - git clone 'https://github.com/rom4s/sourcemod-css34-builder' ../builder
        - powershell '..\builder\run\windows.bat'
      cache:
        - /C/Python38
