branches:
  only:
    - master

language: cpp

git:
  depth: 10

jobs:
  include:
    # Linux
    - name: 'Build on Linux (Ubuntu 14.04)'
      os: linux
      dist: trusty
      python: "3.6"
      before_install:
        # install packages
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get -q update
        - sudo apt-get install -y lib32stdc++6 lib32z1-dev libc6-dev-i386 linux-libc-dev g++9-multilib aria2
        # set exports
        - export WDIR=$(pwd)
        - export PYTHON_VER=3.6.8
        - export CLANG_ARCHIVE=clang-9-ubuntu-14.04-m.tar.xz
        - export PATH=$HOME/.local/bin:$HOME/clang-9/usrbin:$PATH
        # for tests
        - export BITBUCKET_LOGIN=''
        - export GITHUB_LOGIN=''
        - export DISCORD_WEBHOOK=''
        # download python
        - if [[ ! -s "$HOME/.pythonz/etc/bashrc" ]]; then (curl -kL https://raw.github.com/saghul/pythonz/master/pythonz-install | bash); fi
        - source $HOME/.pythonz/etc/bashrc && $(pythonz locate $PYTHON_VER) --version >/dev/null 2>&1 || pythonz install $PYTHON_VER
        - mkdir -p $HOME/.local/bin/ && ln -s $(pythonz locate $PYTHON_VER) $HOME/.local/bin/python
        - python -m pip install --upgrade pip
        - python -m pip install requests uritemplate discord-webhook
        # TODO: move this to builder,
        # for download & selecting required compiler
        - if [ ! -d "$HOME/clang-9/bin" ]; then (aria2c -x 16 -s 16 https://bitbucket.org/rom4s/other.get/downloads/$CLANG_ARCHIVE && echo 'Extract Clang' && time tar -xf $CLANG_ARCHIVE && rm $CLANG_ARCHIVE); fi
      script:
        - git clone 'https://github.com/rom4s/sourcemod-css34-builder' ../builder
        - ../builder/run/linux.sh
      cache:
        - $HOME/.pythonz
        - mysql-5.5
        - hl2sdk-episode1
        - mmsource-1.10
